#!/bin/bash

/usr/bin/apt update -y
/usr/bin/apt upgrade -y
/usr/bin/apt install -y git 
/usr/bin/apt install -y python3 python3-pip
/usr/bin/python3 -m pip install pandas
/usr/bin/apt install -y nginx
